# Generated by Django 5.2.1 on 2025-07-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_registration_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='registration',
            name='ticket_pdf',
            field=models.FileField(blank=True, null=True, upload_to='event_tickets/'),
        ),
    ]
