# Generated by Django 5.2.1 on 2025-07-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_registration_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
